### ISSUE TITLE
change language

### ISSUE THREAD

**Issue by vahidalvandi** [SimonPadbury/bst#11]
hi 
i need change language to RU in this theme please  help me.

very thanks

**Comment by SimonPadbury** [comment]
Hello Vahid,
Sorry, I don't know how to help - the RU language in BST was not done by me. A contributor called Andrey Suvorov ("Spoofi") did it.
https://github.com/SimonPadbury/bst/commits/master/languages/ru_RU.pot?author=spoofi
https://github.com/spoofi
I do not know Andrey, but maybe he can help you. You can contact him here:
I Googled his name and I found this:
https://ru-ru.facebook.com/spoofi

Simon
