### ISSUE TITLE
Error in category on Wordpress 4.4

### ISSUE THREAD

**Issue by Slipkonn** [SimonPadbury/bst#13]
Hi! I am getting an error on wp 4.4 (on 4.3 it works good).
Its in category page:

Warning: Cannot modify header information - headers already sent by (output started at .../wp-content/themes/bst-master/includes/header.php:4) in .../wp-includes/pluggable.php on line 1228

Tested on clean BST, all plugins deactivated

Screen here http://prntscr.com/9h7m2h

**Comment by Slipkonn** [comment]
This line in content.php causes an error 
<?php else: wp_redirect(get_bloginfo('siteurl').'/404', 404); exit; endif; ?>

I replaced it to include some content-none.php
<?php else: get_template_part('includes/loops/content', 'none'); endif; ?>

**Comment by SimonPadbury** [comment]
Thankyou.

I have just made this change you required, in bst/includes/loops/content.php

**Comment by Slipkonn** [comment]
Thanks for quick reply!
I just show my way, maybe there is better way.. i am not too strong in wp
But if you use it now as quick solution, dont forget to add content-none.php in loops, i place there this part from 404

 <div class="alert alert-warning">
    <h1><i class="glyphicon glyphicon-warning-sign"></i> <?php _e('Error', 'bst'); ?> 404</h1>
    <p><?php _e('The page you were looking for does not exist.', 'bst'); ?></p>
</div>

**Comment by SimonPadbury** [comment]
Hi Slipkonn,
Is my new content-none.php (created just now) sufficient?
Simon

**Comment by Slipkonn** [comment]
Yep! it works fine
