### ISSUE TITLE
Parse error: syntax error, unexpected 'endif' (T_ENDIF) in content-single.php

### ISSUE THREAD

**Issue by nicogaldo** [SimonPadbury/bst#14]
in includes/loops/content-single.php delete line 32 please.
![captura](https://cloud.githubusercontent.com/assets/7109610/11964459/b74c674c-a8cc-11e5-9144-a258e7587d4f.PNG)

**Comment by SimonPadbury** [comment]
Thankyou. I just removed the `endif;` on line 31.

**Comment by nicogaldo** [comment]
in content-page.php the same applies

**Comment by SimonPadbury** [comment]
Thankyou. Just fixed.

**Comment by timmysan** [comment]
> I am receiving the same error, any one to assist please

_Parse error: syntax error, unexpected 'endif' (T_ENDIF) in C:\xampp\htdocs\ci\application\views\users\login_view.php on line 8_

`<?php if($this->session->flashdata('errors')); ?>
	<?php echo $this->session->flashdata('errors'); ?>
	<?php endif; ?>`

**Comment by SimonPadbury** [comment]
`login_view.php` is a WordPress core file — not part of BST.

Sorry, I have not worked on BST for many years. This has been superceded by my theme **b4st** (with Bootstrap 4 and Font Awesome 5). https://github.com/SimonPadbury/b4st
