### ISSUE TITLE
function/enqueues.php: Load jquery on header

### ISSUE THREAD

**Issue by danielmrey** [SimonPadbury/bst#16]
function/enqueues.php: I think you need to remove " __FILE__," to load jquery on header, I tested it and it works that way (but don't know why):

wp_register_script('bst-jquery', get_template_directory_uri() .'/js/jquery-1.11.3.min.js', __FILE__, false, '1.11.3', false);

Thanks

**Comment by SimonPadbury** [comment]
Hi Daniel,

OK, I removed it.
