### ISSUE TITLE
Hovernav

### ISSUE THREAD

**Issue by mentolnet** [SimonPadbury/bst#17]
Hello. Is there a way to add Hovernav (sub-menu dropdown and link to the page of the main menu item) to this theme in particular, without having to change to WBST? I am making a few changes to an old website and i need this feature now.
Thank you in advance.

**Comment by SimonPadbury** [comment]
Hi,

I'm on vacation until next week. Sorry I can't look at this until then.

Simon

**Comment by mentolnet** [comment]
No worries, Simon.
Thank you for your quick answer. We´ll talk then,

Hugo

**Comment by SimonPadbury** [comment]
This is old but it may still fit:

https://gist.github.com/SimonPadbury/1d41b4a06bf5cdc8f2c4

Meganav as a gist.

If not, I'll try again next week. 

Simon

**Comment by SimonPadbury** [comment]
Sorry, misread your email..

Here's hovernav:

https://gist.github.com/SimonPadbury/6774640

**Comment by mentolnet** [comment]
Thanks for that, Simon.
Unfortunately, the “hovernav” class is not being added to the navigation, i don´t know why. I am using a child theme and i´ve added the css part to the css/mychildtheme.css file and the .js part to the js/bst.js file of the parent theme.

**Comment by SimonPadbury** [comment]
Next week I will have a bigger screen available. I'll try to help then.

**Comment by mentolnet** [comment]
Thank you again, Simon. Have a nice vacation. Regards,
Hugo

**Comment by SimonPadbury** [comment]
Hi Hugo,

(Note: I just noticed that my Hovernav gist was an early version of my Hovernav, but WBST incorporates an updated version. So I just updated the gist accordingly, blowing away the cobwebs.)

For you: on a fresh download of BST v.2.7.1 from GitHub I got this (below) to work all OK:

(1.) In `bst.css`:

```
/*
HOVERNAV
========
*/

@media (min-width: 768px) {
  .navbar-nav .open ul {
    display: none;
  }
  .navbar-default .navbar-nav > .open > a,
  .navbar-default .navbar-nav > .open > a:hover,
  .navbar-default .navbar-nav > .open > a:focus {
    color: #555;
    background: none;
  }
  .navbar-inverse .navbar-nav > .open > a,
  .navbar-inverse .navbar-nav > .open > a:hover,
  .navbar-inverse .navbar-nav > .open > a:focus {
    color: #969696;
    background: none;
  }
  .navbar-nav .hovernav:hover > .dropdown-menu {
    display: block;
  }
}
```

(2.) And in `bst.js`:

```
  // HOVERNAV
  // ========

  var mq = window.matchMedia('(min-width: 768px)');
  if (mq.matches) {
    $('ul.navbar-nav > li').addClass('hovernav');
  } else {
    $('ul.navbar-nav > li').removeClass('hovernav');
  }
    
  // The addClass/removeClass also needs to be triggered on page resize <=> 768px
    
  function WidthChange(mq) {
    if (mq.matches) {
      $('ul.navbar-nav > li').addClass('hovernav');
    } else {
      $('ul.navbar-nav > li').removeClass('hovernav');
    }
  }
  if (matchMedia) {
    var mq = window.matchMedia('(min-width: 768px)');
    mq.addListener(WidthChange);
    WidthChange(mq);
  }
    
  // Restore "clickable parent links" in HOVERNAV navbar(s)
    
  $('.hovernav a').click(function () {
    window.location = this.href;
  });
```

(This JS above is to be placed **within** the jQuery document ready function, alongside everything else you have put therein):

```
(function ($) {
	
	"use strict";

	$(document).ready(function() {

        // ... put stuff in here ... 

  });    
}(jQuery));
```

Kind regards,

Simon

**Comment by mentolnet** [comment]
Hello Simon and thank you for getting in touch.

Unfortunately, this solution is not working and i don´t understand why. The hovernav class is being added and, other than the clickable parents, everything works - the dropdown works on mouse hover.
I am using a child theme and i added the css code to the css file of my child-theme and the js to the parent but.js. Even when i uploaded a fresh copy of the BST theme and activated it as the website´s theme (with the css you sent added to but.css), the result was the same.

Here is the link, if you want to check it: http://terradrone.mentol.pt <http://terradrone.mentol.pt/>. Do you have any idea why the parent links are not working? Those pages do exist.

Thanks,
Hugo

**Comment by SimonPadbury** [comment]
Hi Hugo,

After some sleep, I found this thought: you can actually add-in any link using JS. But this needs to be done by yourself, not a client who doesn't know code.

Easiest option: Target your parent `<li>` by its ID (supplied by WordPress), and use a `>` CSS3  "direct children" selector to find the parent link:

```
// Example: put this in your jQuery, after 'Hovernav'

$('#menu-item-862 > a').click(function () {
    window.location.href = 'http://google.com';
});
```
Change the Google link to your choice (i.e. the full WordPress permalink of the parent link).

Repeat this snippet for each parent menu item.

**Comment by mentolnet** [comment]
Hello again, Simon.
Sorry for the radio silence but i´m a bit over my head with work. I wanted to thank you for the several emails and ideas - i´ll try both and see if i can first manage this with an older version as suggested.

All the best,
Hugo

**Comment by SimonPadbury** [comment]
OK, no problem

**Comment by mentolnet** [comment]
Hello again, Simon. I am very sorry to bother you again, but i am having a bit of a trouble to get this to work, even with your latest help.
I´ve tried downgrading the Bootstrap version of the parent theme to 3.3.1, as you suggested and nothing. I also tried your latest approach, the jQuery snippet after hovernav to define each link manually.

Here´s what the bt.js looks like right now:

(function ($) {

	"use strict";

	$(document).ready(function() {

		// Comments
		$(".commentlist li").addClass("panel panel-default");
		$(".comment-reply-link").addClass("btn btn-default");

		// Forms
		$('select, input[type=text], input[type=email], input[type=password], textarea').addClass('form-control');
		$('input[type=submit]').addClass('btn btn-primary');

		// You can put your own code in here

		// HOVERNAV
  // ========

  var mq = window.matchMedia('(min-width: 768px)');
  if (mq.matches) {
    $('ul.navbar-nav > li').addClass('hovernav');
  } else {
    $('ul.navbar-nav > li').removeClass('hovernav');
  }

  // The addClass/removeClass also needs to be triggered on page resize <=> 768px

  function WidthChange(mq) {
    if (mq.matches) {
      $('ul.navbar-nav > li').addClass('hovernav');
    } else {
      $('ul.navbar-nav > li').removeClass('hovernav');
    }
  }
  if (matchMedia) {
    var mq = window.matchMedia('(min-width: 768px)');
    mq.addListener(WidthChange);
    WidthChange(mq);
  }

  // Restore "clickable parent links" in HOVERNAV navbar(s)

  $('.hovernav a').click(function () {
    window.location = this.href;
  });

	});


	$('#menu-item-1163 > a').click(function () {
    window.location.href = 'http://terradrone.mentol.pt/pt/imagem-aerea/';
});

}(jQuery));



I really am at a loss here, since all the things you suggested make perfect sense and still they´re not working. Any idea why the latest try is not working?

Thank you once more. Regards,
Hugo

**Comment by SimonPadbury** [comment]
Hello Hugo,

Use the newest Bootstrap 3.3.7 again, and then use this below (or, copy only the lines 44-46):

///////////////////////////////////////////////////////////////

(function ($) {
	
	"use strict";

	$(document).ready(function() {

		// Comments
		$(".commentlist li").addClass("panel panel-default");
		$(".comment-reply-link").addClass("btn btn-default");
	
		// Forms
		$('select, input[type=text], input[type=email], input[type=password], textarea').addClass('form-control');
		$('input[type=submit]').addClass('btn btn-primary');
		
		// You can put your own code in here
    
    // HOVERNAV - navbar dropdown on hover.
    // Uses jQuery Media Query - see http://www.sitepoint.com/javascript-media-queries/
    
    var mq = window.matchMedia('(min-width: 768px)');
    if (mq.matches) {
      $('ul.navbar-nav > li').addClass('hovernav');
    } else {
      $('ul.navbar-nav > li').removeClass('hovernav');
    }
    
    // The addClass/removeClass also needs to be triggered on page resize <=> 768px
    
    function WidthChange(mq) {
      if (mq.matches) {
        $('ul.navbar-nav > li').addClass('hovernav');
      } else {
        $('ul.navbar-nav > li').removeClass('hovernav');
      }
    }
    if (matchMedia) {
      var mq = window.matchMedia('(min-width: 768px)');
      mq.addListener(WidthChange);
      WidthChange(mq);
    }
    
    // Restore "clickable parent links" in HOVERNAV navbar(s)
    
    $('#menu-item-20774 > a')
      .attr('href', 'http://terradrone.mentol.pt/pt/imagem-aerea/')
      .click(function () { window.location.href = 'http://terradrone.mentol.pt/pt/imagem-aerea/'; });
    
    // (Repeat and modify lines 44-46 for each Parent link)
    
  });    
}(jQuery));


///////////////////////////////////////////////////////////////

Explication:

Line 45:
======
.attr('href', 'http://terradrone.mentol.pt/pt/imagem-aerea/‘)

(1.) Problem: these newer Bootstrap 3.x are removing the Parent link, swapping it for href=“#” 
(2.) Pretend solution: This line 45 puts the link in again. So now the browser “status bar” (at the foot of the window) is looking OK. Your visitors are happy, if they look down there at the status bar.

Line 46:
=======
.click(function () { window.location.href = 'http://terradrone.mentol.pt/pt/imagem-aerea/'; });

(3.) Problem: However, as from older Bootstrap, it is also preventing the parent link from being followed.
(4.) Real solution: a new function to enable click to go to your intended webpage.

Ensure that both line 45 and line 46 are to “http://terradrone.mentol.pt/pt/imagem-aerea/“ so that you are not deceiving your visitors...!


Kind regards,

Simon

**Comment by SimonPadbury** [comment]
Another thing,

I find that sometimes WordPress does not refresh the JS files. You sometimes have to browser-refresh your webpage several times before you see a update in your JS.

Simon

**Comment by mentolnet** [comment]
Hello again, Simon.
The problem is now solved, thank you for the extra effort. All the best,

Hugo

**Comment by SimonPadbury** [comment]
Good !

All the best,

Simon
